function op=mfm2struct(f,numeric)
% Create struct from m21fm / m3fm input file so we can check settings
% without having to go into Mike Zero
%
% One day we might be able to tinker with this struct to add more sources
% etc and generate a new MIKE input file. But not yet!
%
% INPUT:
% m21fm file(s) - (should work for m3fm files but not tested yet).
%
% Optional input:
% numeric (false) - if true, try to convert strings to numeric. 
%
% OUTPUT:
% struct - fields in CAPITALS are derived from m21fm file. We also store
% the file name and name of the MIKE Engine (e.g. FemEngineHD)-
%
% Note - for use in matlab, probably want numeric = true. 
% However, if we want to use output struct for generating new .m21fm file
% need numeric = false so values aren't tinkered with (e.g. 2.0 changing to
% 2). MikeZero seems quite picky about this!


if nargin<2
    numeric=true;
end

f=cellstr(f);
N=length(f);
if N>1
    op=cellfun(@Mike.mfm2struct,f);
    return
end
f=char(f);

% We should have a filename
if ~isfile(f) % if not...
    error('''%s'' isn''t a file :-(',f) % ... we have a problem
end

txt=readTxtFile(f);
% Header
k=stringFinder(txt,'[','output','index','first',1); % data starts here!
header=txt(1:k-1);
% Originally, tested this with .m21fm file with [FemEngineHD].
% But might not always be this- e.g. Gunda's .m2m file was [FemEngine];
% Find relevant name:
engineName=txt{find(contains(txt,'['),1,'first')};
engineName=strrep(engineName,'[','');
engineName=strrep(engineName,']','');
% NB a struct called this will be generated by processing input file.
% We add it to our output struct at the end.

% First up, add filename to struct
cmd=sprintf('%s.FileName=''%s''',engineName,f);
evalc(cmd);
% Add engine name:
cmd=sprintf('%s.EngineName=''%s''',engineName,engineName);
evalc(cmd);

%
N=length(txt);
cmdArray=cell(N,1);
astr={};
for i=1:N
    row=txt{i};
    row=strtrim(row);
    if isempty(row)
        continue
    end
    %    fprintf('%d : row text = ''%s''\n',i,row)
    if strcmp(row(1),'[')
        row=strrep(row,'[','');
        row=strrep(row,']','');
        astr{end+1}=row;
    elseif contains(row,'EndSect')
        astr(end)=[];
    elseif ~contains(row,'=') % Ignore comments
        continue
    else
        % Find value - NB don't try to convert to numeric!! This changes
        % e.g. 2.0 to 2 and .m21fm file created from this struct using
        % struct2text won't work! 
        [a,b]=splitStringByEqualsSign(row,'minAscii',32,'numeric',numeric);
        fn=sprintf('%s%s',sprintf('%s.',astr{:}),char(a));
        %    fprintf('Fieldname = ''%s''\n',fn)
        if iscell(b)
            b=b{1};
        end
        if ischar(b)
            b=strtrim(b);
        end
        cmd=sprintf('%s=b',fn);
        try
            evalc(cmd);
            cmdArray{i}=sprintf('%s = %s',fn,tdisp(b));
        catch err
            disp(err)
            warning('problem with command')
            disp(cmd)
        end
    end
end
cmd=sprintf('op=%s',engineName);
evalc(cmd);
op.header=header;
%op=struct('FileName',f);
% Add engineName struct we created in loop above:
%cmd=sprintf('op.(''%s'')=%s',engineName,engineName);
%evalc(cmd);
% Add commands for checking:
cmdArray(cellfun(@isempty,cmdArray))=[];
op.evalcCommands=cmdArray;


